context:
  name: msgpack-tools
  version: '0.6'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ludocode/${{ name }}/releases/download/v${{ version }}/msgpack-tools-${{ version }}.tar.gz
  sha256: 98c8b789dced626b5b48261b047e2124d256e5b5d4fbbabdafe533c0bd712834

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - make

tests:
  - script:
      - msgpack2json -v
      - json2msgpack -v
  - package_contents:
      bin:
        - json2msgpack
        - msgpack2json
      files:
        - share/man/man1/json2msgpack.1
        - share/man/man1/msgpack2json.1

about:
  homepage: https://github.com/ludocode/msgpack-tools
  repository: https://github.com/ludocode/msgpack-tools
  summary: Command-line tools for converting between MessagePack and JSON / msgpack.org
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
